# Maicraft插件配置模板
[inner]
version = "0.2.0"

[bot]
player_name = "Mai"
bot_name = "麦麦"

[game]
goal = "以合适的步骤，建立营地，挖到16个钻石，并存储"

[llm]
model = "gpt-4o"
temperature = 0.2
api_key = "your-api-key"  # 可选，如果不设置将使用环境变量
base_url = "https://api.openai.com/v1"  # 可选，用于自定义API端点
max_tokens = 1024

[llm_fast]
model = "gpt-4o-mini"
temperature = 0.2
api_key = "your-api-key"  # 可选，如果不设置将使用环境变量
base_url = "https://api.openai.com/v1"  # 可选，用于自定义API端点
max_tokens = 1024

[visual]
enable = false


[vlm]
model = "gpt-4o"
temperature = 0.3
api_key = "your-api-key"
base_url = "https://api.openai.com/v1"
max_tokens = 1024

[logging]
# level 可选: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR, CRITICAL
level = "INFO"
# 是否启用JSON Lines格式文件输出（控制台始终为彩色格式）
enable_json = false
# 是否输出日志到文件
log_to_file = true
# 日志目录
log_dir = "logs"
# 日志轮转策略 (推荐按大小: "10 MB", "50 MB", "100 MB" 或按时间: "1 day", "6 hours", "1 hour")
rotation = "10 MB"
# 日志保留策略 (推荐: "3 days", "1 week", "10 files")
retention = "3 days"
# 是否启用层次化日志记录 (不同级别输出到不同文件)
enable_hierarchical_logging = true
# 内存中保留的最近日志条数 (用于快速查询)
max_recent_logs = 1000