# 方块缓存系统配置文件

[block_cache]
# 基本设置
max_cache_size = 10000          # 最大缓存方块数量
cleanup_interval = 3600         # 自动清理间隔（秒）
enable_auto_cleanup = true      # 是否启用自动清理
cleanup_percentage = 20         # 清理时移除的方块百分比

# 持久化设置
auto_save_interval = 1800       # 自动保存间隔（秒）
backup_enabled = true           # 是否启用备份
backup_count = 5                # 保留的备份文件数量
cache_file_path = "block_cache.json"  # 缓存文件路径

# 日志设置
log_level = "INFO"              # 日志级别：DEBUG, INFO, WARNING, ERROR
log_cache_operations = true     # 是否记录缓存操作日志
