# -*- coding: utf-8 -*-
# Generated by MaiAgent after successful task execution

async def collect_gravel_and_sand(bot):
    # 检查当前物品数量
    gravel_count = 0
    sand_count = 0
    
    # 统计当前物品栏中的沙砾和沙子数量
    for item in await bot.inventory:
        if item.name == "gravel":
            gravel_count += item.count
        elif item.name == "sand":
            sand_count += item.count
    
    await bot.chat(f"当前收集进度: 沙砾{gravel_count}/20, 沙子{sand_count}/30")
    
    # 采集沙砾
    if gravel_count < 20:
        await bot.chat("开始采集沙砾...")
        success, gravel_blocks = await bot.find_blocks("gravel", 64)
        if success and gravel_blocks:
            for block in gravel_blocks:
                if gravel_count >= 20:
                    break
                x, y, z = block.position.x, block.position.y, block.position.z
                await bot.move(x, y+1, z)  # 移动到方块上方
                success, exists = await bot.mine_block(x, y, z, False)
                if success and exists:
                    gravel_count += 1  # 假设每个沙砾方块掉落1个物品
                    await bot.chat(f"采集沙砾: 当前{gravel_count}/20")
    
    # 采集沙子
    if sand_count < 30:
        await bot.chat("开始采集沙子...")
        success, sand_blocks = await bot.find_blocks("sand", 64)
        if success and sand_blocks:
            for block in sand_blocks:
                if sand_count >= 30:
                    break
                x, y, z = block.position.x, block.position.y, block.position.z
                await bot.move(x, y+1, z)  # 移动到方块上方
                success, exists = await bot.mine_block(x, y, z, False)
                if success and exists:
                    sand_count += 1  # 假设每个沙子方块掉落1个物品
                    await bot.chat(f"采集沙子: 当前{sand_count}/30")
    
    # 最终检查
    if gravel_count >= 20 and sand_count >= 30:
        await bot.chat("任务完成: 已收集足够的沙砾和沙子")
    else:
        await bot.chat(f"收集未完成: 沙砾{gravel_count}/20, 沙子{sand_count}/30")