# -*- coding: utf-8 -*-
# Generated by MaiAgent after successful task execution

# main function
async def craftStonePickaxe(bot):
    # 检查所需材料
    inventory = await bot.inventory
    cobblestone_count = sum(item.count for item in inventory if item.name == "cobblestone")
    stick_count = sum(item.count for item in inventory if item.name == "stick")
    
    if cobblestone_count < 3:
        await bot.chat("圆石不足，无法合成石镐。")
        return False
    if stick_count < 2:
        await bot.chat("木棍不足，无法合成石镐。")
        return False

    # 尝试合成石镐
    success, result_text = await bot.craft_item("stone_pickaxe", 1)
    
    if success:
        await bot.chat("成功合成石镐！")
        # 验证是否真的在物品栏中
        inventory = await bot.inventory
        has_pickaxe = any(item.name == "stone_pickaxe" for item in inventory)
        if has_pickaxe:
            await bot.chat("任务完成：已获得石镐。")
            return True
        else:
            await bot.chat("合成返回成功但未找到石镐，请检查问题。")
            return False
    else:
        await bot.chat(f"合成失败：{result_text}")
        return False