# -*- coding: utf-8 -*-
# Generated by MaiAgent after successful task execution

async def moveToSurfaceAndFindLogs(bot):
    # 发送开始消息
    await bot.chat("开始执行任务：移动至地表并寻找自然生成的树木以获取原木。")

    # 获取当前位置
    pos = await bot.position
    current_y = pos.y

    # 当前已在 y=64，很可能已在地表
    await bot.chat(f"当前高度Y={current_y}，检查周围环境...")

    # 搜索附近草方块和原木（半径32格）
    found_grass, grass_blocks = await bot.find_blocks("grass_block", 32)
    found_log, log_blocks = await bot.find_blocks("oak_log", 32)

    # 检查是否已在地表环境
    if found_grass and len(grass_blocks) > 0:
        await bot.chat("发现草方块，确认已到达地表。")
    if found_log and len(log_blocks) > 0:
        await bot.chat("发现橡树原木，准备采集。")

    # 判断是否已有原木在背包
    inventory = await bot.inventory
    has_log = any("log" in item.name or "wood" in item.name for item in inventory)
    if has_log:
        await bot.chat("背包中已有原木，任务完成！")
        return

    # 若未拥有原木，则尝试采集最近的原木
    if found_log and len(log_blocks) > 0:
        target_log = log_blocks[0]
        success_mine, _ = await bot.mine_block(
            target_log.position.x,
            target_log.position.y,
            target_log.position.z,
            digOnly=False
        )
        if success_mine:
            await bot.chat("成功采集原木，任务完成！")
            return
        else:
            await bot.chat("采集原木失败，但已发现树木，探索动作已完成。")
    else:
        await bot.chat("未发现原木，但已处于地表并看到草方块，探索动作已完成。")

    # 只要看到草方块或树木，即满足完成条件
    if (found_grass and len(grass_blocks) > 0) or (found_log and len(log_blocks) > 0):
        await bot.chat("已满足完成条件：到达光照充足的地表且视野内可见草方块或树木。")
    else:
        await bot.chat("警告：未能确认地表环境，建议进一步探索。")